### ISSUE TITLE
Docker image tags used in Docker-compose deployment need updating.

### ISSUE THREAD

**Issue by aznashwan** [finos/legend#429]
## Bug Report

NOTE: this report assumes the fixes listed in #428 are already applied.

All Docker-compose-based deployment methods lead to crashing SDLC and Engine containers due to [the image tags used](https://github.com/finos/legend/blob/master/installers/docker-compose/dependencies.env#L4-L6) being very old.

### Steps to Reproduce:
Followed the below-linked deployment instructions word-for-word:
https://github.com/finos/legend/blob/master/installers/docker-compose/legend-studio-dev/README.md
https://github.com/finos/legend/blob/master/installers/docker-compose/legend-with-remote-gitlab/README.md
https://github.com/finos/legend/blob/master/installers/docker-compose/legend/README.md

### Expected Result:
A working Legend stack. (assuming all other manually-done configurations were correct)

### Actual Result:
SDLC and Engine containers fail on startup.

Container STDOUT/ERR output shows the following:
Note that the below output is from the `legend-with-remote-gitlab` bundle, but the contents is identical to the other save for the "Waiting for Gitlab..." messages which show up until the Gitlab container boots.

Engine:
```bash
root@cloudbase:~/# docker logs engine
11:49:26.860 [main] INFO Alloy Execution Server - {"duration":0.0,"eventType":"URL_FACTORY_REGISTERED","message":"Registered Alloy URL Factory","timeStamp":"2021-08-30 11:49:25.841","user":"_UNKNOWN_"}
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
io.dropwizard.configuration.ConfigurationParsingException: /config/config.json has an error:
  * Unrecognized field at: vaults
    Did you mean?:
      - pac4j
      - metrics
      - server
      - swagger
      - logging
        [4 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at org.finos.legend.engine.server.Server.main(Server.java:84)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "vaults" (class org.finos.legend.engine.server.ServerConfiguration), not marked as ignorable (9 known properties: "metadataserver", "metrics", "deployment", "opentracing", "filterPriorities", "logging", "server", "pac4j", "swagger"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.finos.legend.engine.server.ServerConfiguration["vaults"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1597)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1575)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
```

SDLC:
```bash
root@cloudbase:~/# docker logs sdlc
io.dropwizard.configuration.ConfigurationParsingException: /config/config.yml has an error:
  * Failed to parse configuration at: projectStructure.extensionProvider; Could not resolve type id 'org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider' as a subtype of `org.finos.legend.sdlc.server.project.extension.ProjectStructureExtensionProvider`: no such class found
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.finos.legend.sdlc.server.config.LegendSDLCServerConfiguration["projectStructure"]->org.finos.legend.sdlc.server.project.config.ProjectStructureConfiguration["extensionProvider"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:156)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at org.finos.legend.sdlc.server.LegendSDLCServer.main(LegendSDLCServer.java:34)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider' as a subtype of `org.finos.legend.sdlc.server.project.extension.ProjectStructureExtensionProvider`: no such class found
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.finos.legend.sdlc.server.config.LegendSDLCServerConfiguration["projectStructure"]->org.finos.legend.sdlc.server.project.config.ProjectStructureConfiguration["extensionProvider"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1761)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1268)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:104)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:527)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1292)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
```

Note that I could not find a way to get the full stack traces (i.e. expand those '... 6 more' bits from the trace).
Any suggestions on that front would be appreciated.

### Environment:
OS: Ubuntu 20.04, fully updated as of the time of writing
Docker: version 20.10.7, build 20.10.7-0ubuntu1~20.04.1
Docker-compose: 1.29.2 (installed from Pypi via `pip` since the version shipped with Ubuntu refused to handle Docker-compose templates versioned '3.8')

Images:
root@cloudbase:~/legend/installers/docker-compose/legend-with-remote-gitlab# docker image ls
REPOSITORY                   TAG       IMAGE ID       CREATED        SIZE
mongo                        4.0       9650de099aeb   3 weeks ago    430MB
finos/legend-sdlc-server     0.24.0    8b5661a9ae91   5 months ago   696MB
finos/legend-engine-server   2.21.0    7fe43405f8fd   5 months ago   809MB
finos/legend-studio          0.2.16    0832292e704f   5 months ago   702MB

### Additional Context:

As a general suggestion, I feel that maintaining a standardized tag (e.g. 'latest' or 'edge') for the latest Docker image versions uploaded to Dockerhub would be handy.
Currently, one must look up the latest version manually on FINOS' Dockerhub page, which can be prone to errors on top of being inconvenient.

**Comment by aznashwan** [comment]
As mentioned in #430, the issue was due to the Docker image tags used by Docker-compose being really old.

I'd still suggest that a standardized tagging system be used for the latest Docker image versions uploaded to Dockerhub.
