### ISSUE TITLE
HTTP ERROR 500 org.pac4j.core.exception.TechnicalException: clientId cannot be blank

### ISSUE THREAD

**Issue by koernigo** [finos/legend#468]
Ran the docker-compose installer.

After all the containers are up, I get the following error message in the Browser (http://localhost:8080/studio)

HTTP ERROR 500 org.pac4j.core.exception.TechnicalException: clientId cannot be blank
URI:	/studio
STATUS:	500
MESSAGE:	org.pac4j.core.exception.TechnicalException: clientId cannot be blank
SERVLET:	assets
CAUSED BY:	org.pac4j.core.exception.TechnicalException: clientId cannot be blank
Caused by:
org.pac4j.core.exception.TechnicalException: clientId cannot be blank
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:109)
	at org.pac4j.core.util.CommonHelper.assertNotBlank(CommonHelper.java:121)
	at org.pac4j.core.util.CommonHelper.assertNotBlank(CommonHelper.java:131)
	at org.pac4j.oidc.config.OidcConfiguration.internalInit(OidcConfiguration.java:123)
	at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:20)
	at org.pac4j.oidc.config.OidcConfiguration.findProviderMetadata(OidcConfiguration.java:157)
	at org.pac4j.oidc.credentials.authenticator.OidcAuthenticator.<init>(OidcAuthenticator.java:57)
	at org.finos.legend.server.pac4j.gitlab.GitlabClient$1.<init>(GitlabClient.java:111)
	at org.finos.legend.server.pac4j.gitlab.GitlabClient.clientInit(GitlabClient.java:109)
	at org.pac4j.core.client.IndirectClient.internalInit(IndirectClient.java:58)
	at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:20)
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:93)
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:79)
	at org.pac4j.core.engine.DefaultSecurityLogic.redirectToIdentityProvider(DefaultSecurityLogic.java:217)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:149)
	at org.pac4j.j2e.filter.SecurityFilter.internalFilter(SecurityFilter.java:93)
	at org.pac4j.j2e.filter.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:81)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.finos.legend.server.shared.bundles.HostnameHeaderBundle$Enricher.doFilter(HostnameHeaderBundle.java:62)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
	at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:37)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by beekemarie** [comment]
Thanks @koernigo! Adding @maoo to this thread to look into this.

**Comment by sidsahai** [comment]
Hi @beekemarie @koernigo 

Were you guys able to find a solution to this one?

**Comment by akphi** [comment]
Hi, please check the generated config file, I think the default is at `~/legend-temp`. There might be a problem with the generated config (potentially for `finos/legend-studio` which does not have `clientId` set properly (as indicated by the error message)). If you post the config here, maybe one of us can help debugging this.

**Comment by sidsahai** [comment]
Can client id be any arbitrary number? I can see the httpConfig.json has clientid and secret as blank.

**Comment by akphi** [comment]
yeah you would need to fill that out. I believe that should have been taken care of if before running `compose` you generate the certs with the right config, that means the `config.properties` file.

**Comment by sidsahai** [comment]
I am trying to run it on my laptop with docker desktop. During running the ./scripts/setup.sh ./config.properties on my laptop in windows powershell it gave error that openssl and keytool commands on lines could not be found however, other things ran fine. 

I had to manually update the MONGO_USER and MONGO_PASSWORD values in the generated .env file after running ./scripts/setup.sh ./config.properties

I am unsure how to update the following:
          "clientId" : "",
          "secret": "",
because these two are in the ~legend-temp\generated-configs\studio\httpConfig.json. This file(httpConfig.json) gets generated as soon as I run the  docker-compose --env-file ~legend-temp/.env up --detach

**Comment by akphi** [comment]
The clientId and secret are meant for your Gitlab Oauth application, you can follow this guide here on how to get them

https://github.com/finos/legend/blob/master/installers/docker-compose/legend-studio-dev/README.md#gitlab-oauth-config-setup

**Comment by epsstan** [comment]
Closing this issue as stale. Please re-open if still relevant.
