### ISSUE TITLE
Jar File Creation Failing in GitLab for Legend Projects

### ISSUE THREAD

**Issue by smorres** [finos/legend#626]
### Steps to Reproduce:
 1. Deployed latest released docker images for studio, engine and sdlc. I am using GitLab-ce and a GitLab runner that I also spun up in a container. 
 2. created a simple model to model mapping with a service in studio, firstName , lastName to full name.
 3. added a proxy configuration to my gitlab-ci.yml, which I have attached. I am able to pull dependencies from maven central with this setup, so proxy is working as expected. 
 4. Rerun the CI/CD job, and it fails

### Expected Result:
Jar file artifacts generated in Gitlab

### Actual Result:
Job fails with the following error:

Exception in thread "main" java.util.ServiceConfigurationError: org.finos.legend.sdlc.serialization.EntitySerializer: Provider org.finos.legend.sdlc.protocol.pure.v1.PureEntitySerializer could not be instantiated

Caused by: java.lang.NoSuchMethodError: 'org.finos.legend.engine.protocol.pure.v1.extension.ProtocolSubTypeInfo$Builder org.finos.legend.engine.protocol.pure.v1.extension.ProtocolSubTypeInfo$Builder.withSubtypes(java.util.List)'

-Full log with mvn dependency tree attached

### Environment:
finos/legend-studio:5.0.0 | finos/legend-engine-server:3.1.0 | finos/legend-sdlc-server:0.75.0
gitlab-ce 14.6.1
gitlab-runner 15.9.1

attached a copy of the projects pom.xml, and the updated gitlab-ci.yml

Error Log: [error_log_gitlab-simpletest-job-455-attempt.txt](https://github.com/finos/legend/files/10982364/error_log_gitlab-simpletest-job-455-attempt.txt)
gitlab-ci.yml: [gitlab-ci.txt](https://github.com/finos/legend/files/10982376/gitlab-ci.txt)
pom.xml: [pom.txt](https://github.com/finos/legend/files/10982377/pom.txt)

uploaded attachments as txt files- github does not support uploading xml or yml here for some reason

**Comment by smorres** [comment]
I downloaded the project and tested running a mvn clean deploy from an IDE and I am getting the same error
`Exception in thread "main" java.util.ServiceConfigurationError: org.finos.legend.sdlc.serialization.EntitySerializer: Provider org.finos.legend.sdlc.protocol.pure.v1.PureEntitySerializer could not be instantiated

                at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)

                at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)

                at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)

                at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)

                at org.finos.legend.sdlc.serialization.EntitySerializers.indexByName(EntitySerializers.java:57)

                at org.finos.legend.sdlc.serialization.EntitySerializers.getAvailableSerializersByName(EntitySerializers.java:46)

                at org.finos.legend.sdlc.entities.EntityMojo.getSerializationSpecs(EntityMojo.java:101)

                at org.finos.legend.sdlc.entities.EntityMojo.execute(EntityMojo.java:61)

                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)

                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)

                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)

                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)

                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)

                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)

                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)

                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)

                at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)

                at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)

                at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)

                at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)

                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)

                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)

                at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

                at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

Caused by: java.lang.NoSuchMethodError: org.finos.legend.engine.protocol.pure.v1.extension.ProtocolSubTypeInfo.newBuilder(Ljava/lang/Class;)Lorg/finos/legend/engine/protocol/pure/v1/extension/ProtocolSubTypeInfo$Builder;

                at org.finos.legend.engine.external.format.flatdata.FlatDataProtocolExtension.lambda$getExtraProtocolSubTypeInfoCollectors$1553c525$1(FlatDataProtocolExtension.java:34)

                at org.eclipse.collections.impl.lazy.FlatCollectIterable.lambda$each$35135c79$1(FlatCollectIterable.java:42)

                at org.eclipse.collections.impl.list.fixed.SingletonList.each(SingletonList.java:207)

                at org.eclipse.collections.impl.AbstractRichIterable.forEach(AbstractRichIterable.java:581)

                at org.eclipse.collections.impl.utility.Iterate.forEach(Iterate.java:131)

                at org.eclipse.collections.impl.lazy.FlatCollectIterable.each(FlatCollectIterable.java:42)

                at org.eclipse.collections.impl.AbstractRichIterable.forEach(AbstractRichIterable.java:581)

                at org.finos.legend.engine.protocol.pure.v1.PureProtocolObjectMapperFactory.lambda$withPureProtocolExtensions$3(PureProtocolObjectMapperFactory.java:74)

                at org.eclipse.collections.impl.list.mutable.FastList.each(FastList.java:603)

                at org.eclipse.collections.impl.AbstractRichIterable.forEach(AbstractRichIterable.java:581)

                at org.eclipse.collections.api.InternalIterable.forEach(InternalIterable.java:58)

                at org.finos.legend.engine.protocol.pure.v1.PureProtocolObjectMapperFactory.withPureProtocolExtensions(PureProtocolObjectMapperFactory.java:73)

                at org.finos.legend.engine.protocol.pure.v1.PureProtocolObjectMapperFactory.withPureProtocolExtensions(PureProtocolObjectMapperFactory.java:63)

                at org.finos.legend.engine.protocol.pure.v1.PureProtocolObjectMapperFactory.withPureProtocolExtensions(PureProtocolObjectMapperFactory.java:53)

                at org.finos.legend.sdlc.protocol.pure.v1.PureToEntityConverter.<init>(PureToEntityConverter.java:36)

                at org.finos.legend.sdlc.protocol.pure.v1.PureEntitySerializer.<init>(PureEntitySerializer.java:46)

                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

                at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)

                ... 29 more`
