### ISSUE TITLE
legend data model consumption errors.

### ISSUE THREAD

**Issue by Rajaram1604** [finos/legend#651]
Have found this maven dependency **org.finos.legend-community:legend-delta:X.Y.Z** and this python package **legend-delta==X.Y.Z** for Apache spark and are able to consume the legend data model from Azure Databricks by using the Scala and python language respectively and this is the repository for the library **https://github.com/finos/legend-community-delta**.

**Python**
Also, trying to consume the data model from the Python framework. Just wanted to know if Is there any Python package available for legend data model consumption. Please let us know.
**Java application**
Have been using this **service-execution** maven dependency for the consumption but getting errors due to the application being unable to retrieve the API token from the default Vault**

Note: The legend data model has H2 data source connectivity that can consume from Java application, where there is no property configured in the vault to establish the authentication because chosen H2 Default authentication.

**Error Trace:**

Caused by: org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionException: java.lang.Exception: Could not retrieve API token from default Vault
	at org.finos.legend.engine.plan.execution.stores.relational.connection.authentication.strategy.ApiTokenAuthenticationStrategy.resolveCredential(ApiTokenAuthenticationStrategy.java:82)
	at org.finos.legend.engine.plan.execution.stores.relational.connection.authentication.strategy.ApiTokenAuthenticationStrategy.handleConnection(ApiTokenAuthenticationStrategy.java:62)
	at org.finos.legend.engine.plan.execution.stores.relational.connection.driver.DriverWrapper.connect(DriverWrapper.java:73)
	... 50 more
Caused by: java.lang.Exception: Could not retrieve API token from default Vault
	... 53 more

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
