### ISSUE TITLE
Issue with Legend Pure IDE and Omnibus Variant Feedback

### ISSUE THREAD

**Issue by reyes-michael** [finos/legend#796]
Hi FINOS Team!

I am currently working on crafting a Legend metamodel on the [OWL 2 Web Ontology Language](https://www.w3.org/TR/owl2-syntax/). I was able to get the Legend Omnibus - slim version working, but I want to run the Legend Pure IDE to write Pure Code to help create validations on the meta model as I am building it. 

Side Note:
A great variant to have is the slim with the Legend Pure IDE! I think it looks sick and it would be awesome to have that included with the slim.

When I try the run the full version, I am able to navigate to the Legend Pure IDE, but I get the following error message: 

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

![image](https://github.com/finos/legend/assets/42794331/49d2043f-ce00-4b13-9edf-ae5457ce79be)

I also get this message when I try to run commands in the Legend Pure IDE terminal. I am running the docker build and run scripts from the Legend Omnibus for the full variant using the .env arguments as on the [Github repo](https://github.com/finos/legend/tree/master/installers/omnibus). I am also on Windows11 with WSL using git-bash to run the scripts.

I'm not quite sure where the issue is in the setup? I looked at the Github questions and previous issues and I did not find anything.
If there is something I am missing or this is an issue, please let me know.

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by reyes-michael** [comment]
Updating the thread:

After looking into the Nginx configs, turns out I was accessing the Pure IDE from the wrong port number.
I am able to use the Legend Pure IDE and I am able to run the Welcome.pure go() function, so that's awesome. Also, I seem to be getting an error when trying to create a new directory or file via the terminal. Currently investigating if it related to Docker Permissions, but the logging in the Engine or the IDE doesn't capture this.

`java.lang.IllegalArgumentException: Cannot create folder /owlFolder
  at org.finos.legend.pure.m3.serialization.filesystem.usercodestorage.composite.CompositeCodeStorage.createFolder(CompositeCodeStorage.java:428)
  at org.finos.legend.pure.ide.light.api.FileManagement.newFolder(FileManagement.java:129)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
  at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
  at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
  at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
  at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
  at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
  at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
  at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
  at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:37)
  at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)
  at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
  at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
  at org`

![image](https://github.com/finos/legend/assets/42794331/9ff66f45-cef2-4859-b812-01bb84342de0)

**Comment by reyes-michael** [comment]
After finding that it was not a docker container permissions issue, I checked out the [legend-engine](https://github.com/finos/legend-engine) project in IntelliJ and built the project locally. After dealing with some build failures due to asserts failing (I suspect that it has to due with Linux and Windows char diffs), I built and ran the project locally and still the encountered the issue. As it turns out, the Omnibus uses the following object [PureIDELight_NoExtension](https://github.com/finos/legend-engine/blob/master/legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDELight_NoExtension.java)  to launch the IDE. This object loads in the core and pure_ide Code Repositories using a ClassLoaderCodeStorage object that implements an ImmutableRepositoryCodeStorage, this explains why the CompositeCodeStorage was throwing an issue when creating a folder.

After some investigating, it turns out that there is another IDE object we can run that gives not only the full Legend packages to use but also allows for creation of files and folders for the project for certain directories. The [PureIDELight](https://github.com/finos/legend-engine/blob/7e73cf11f913d72cf5dd0d10d29a8a8c2581fd5a/legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light-http-server/src/main/java/org/finos/legend/engine/ide/PureIDELight.java#L27) object uses a MutableFSCodeStorage object to load and store all the code repositories. 
![Pure_IDE](https://github.com/finos/legend/assets/42794331/4cf53dd4-c6c2-469d-9df6-b58995d167b1)

So a change could be done with how the Omnibus packages the script for the IDE, if it can be changed to using the PureIDELight object, this would allow for people to experiment more indepth with the language by running the Docker script outright. It is worth noting that when checkout the legend-engine project, you can add your own Code Repositories. Adding a custom CodeRepositoryProvider and the required resources like any Pure Code and definition.json needed, would allow the IDE to load in the code you are writing.

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.

**Comment by rahulw007** [comment]
@reyes-michael - can you suggest what was the final ngnix config that worked for you?

**Comment by rahulw007** [comment]
Thanks for your response, this is helpful!
wrt the PureIDELight, I am currently running PureIDELight_NoExtension
which comes with the omnibus default installation. Interesting to know
you managed to run PureIDELight, is there any config change for that?
Did you run independently outside the omnibus installation? Also did
it involve any config changes? You had mentioned about ngnix config
changes which i was interested in, currently my process is failing
with 500 error when it is trying to execute /fileAsJson with the
welcome.pure file.


On Mon, 6 Jan 2025 at 21:06, Michael Reyes ***@***.***> wrote:
>
> Changing this line in the SDLC config from - /api/auth/authorized -> to - /api/auth/authorize fixes the issue for authorization when connecting to an on prem gitlab instance from this file: https://github.com/finos/legend/blob/master/installers/omnibus/components/sdlc/config/config.yml line 46.
>
> Else, in this thread, I just ran the The PureIDELight object explicitly to get the IDE up
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
Rahul Waghmare.......

**Comment by akphi** [comment]
@reyes-michael Thank you for the thorough walkthrough. I'm glad you showed interest in the omnibus and Legend Pure IDE. Like you said, it's a great place to take a sneak peak at the power of Pure.

When I have time, I will see if we could swap out to use the "full" version of `PureIDELight`. However, it would add substantial start time though since it loads a fair amount of extensions, that's the main motivation for us going with the `PureIDELight_NoExtension` in the first place.

Regarding your fix for `nginx`, we'll have to take a look, `/api/auth/authorized` is an endpoint that is needed to be bypassed.

**Comment by akphi** [comment]
Regarding if we could have a separate variant for Pure IDE, we would have to decline the request at the moment. Pure IDE is really meant for editing Pure and thus, the best place to use it would be to build from source within [finos/legend-engine](https://github.com/finos/legend-engine). The version included here is meant as a playground. If we see growing interest, we would revisit that decision.

**Comment by reyes-michael** [comment]
> Regarding if we could have a separate variant for Pure IDE, we would have to decline the request at the moment. Pure IDE is really meant for editing Pure and thus, the best place to use it would be to build from source within [finos/legend-engine](https://github.com/finos/legend-engine). The version included here is meant as a playground. If we see growing interest, we would revisit that decision.

Fair, I meant to each their own! Sometimes you have to use both in unusual ways to advance business outcomes

**Comment by rahulw007** [comment]
thanks both! @reyes-michael - i will try running the full version of PureIDELight!
